name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
    - name: Build Docker Image
      run: |
        docker build . --file ./containers/coordinates/Dockerfile --tag coordinates:1.0
        
    - name: Push Docker Image
      run: |
        docker push $DOCKER_USERNAME/global-data-pipeline
