name: Docker Image Push

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
    - name: Build Docker Image
      run: |
        docker build . --file ./containers/air_quality/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/global-data-pipeline:air_quality
        docker build . --file ./containers/coordinates/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/global-data-pipeline:city_coordinates
        docker build . --file ./containers/weather/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/global-data-pipeline:city_weather
        docker build . --file ./containers/countries/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/global-data-pipeline:country_statistics
        docker build . --file ./containers/population/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/global-data-pipeline:population
        

        
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/global-data-pipeline:air_quality
        docker push ${{ secrets.DOCKER_USERNAME }}/global-data-pipeline:city_coordinates
        docker push ${{ secrets.DOCKER_USERNAME }}/global-data-pipeline:city_weather
        docker push ${{ secrets.DOCKER_USERNAME }}/global-data-pipeline:country_statistics
        docker push ${{ secrets.DOCKER_USERNAME }}/global-data-pipeline:population